name: Deploy to S3

on:
  push:
    branches:
    - main
# not sure what region to use. 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      run: "aws configure set aws_access_key_id  \
      ${{ secrets.ACCESS_KEY_ID }} && \
      aws configure set aws_secret_access_key \
      ${{ secrets.SECRET_KEY }} && \
      aws configure set default.region \
      ${{ secrets.AWS_REGION }}"
    - name: Deploy to S3
      run: aws s3 sync . s3://cam-mac-mac-cam-glue-bucket/ --delete