name: Deploy to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      run: aws configure set role_arn ${{ secrets.AWS_ROLE_ARN }} && aws configure set region ${{ secrets.AWS_REGION }}
    - name: Deploy to S3
      run: aws s3 sync . s3://cam-mac-mac-cam-glue-bucket/ --delete